# Generated by Django 3.0.2 on 2020-02-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_route',
            field=models.CharField(default='occasions:occasions.urls.some_view', help_text='default route upon successful login', max_length=50),
        ),
    ]
