# Generated by Django 3.0.2 on 2020-01-13 02:58

import attendees.persons.models.enum
import attendees.persons.models.utility
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=25, null=True)),
                ('first_name2', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('last_name2', models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                ('other_name', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('UNSPECIFIED', 'unspecified')], default=attendees.persons.models.enum.GenderEnum['UNSPECIFIED'], max_length=11)),
                ('actual_birthday', models.DateTimeField(blank=True, null=True)),
                ('estimated_birthday', models.DateTimeField(blank=True, null=True)),
                ('medical_concern', models.CharField(default='Food allergy: nothing', max_length=50)),
            ],
            options={
                'db_table': 'persons_attendees',
                'ordering': ['last_name', 'first_name'],
            },
            bases=(attendees.persons.models.utility.Utility, models.Model),
        ),
    ]
