# Generated by Django 3.0.5 on 2020-05-02 15:48

from uuid import uuid4
from django.contrib.postgres.fields.jsonb import JSONField
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', model_utils.fields.UUIDField(default=uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.SmallIntegerField(db_index=True, default=0)),
                ('infos', JSONField(blank=True, default=dict, help_text='Example: {"2010id": "3"}. Please keep {} here even no data', null=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'db_table': 'persons_families',
                'ordering': ('display_order', '-modified'),
            },
        ),
        migrations.AddIndex(
            model_name='family',
            index=django.contrib.postgres.indexes.GinIndex(fields=['infos'], name='family_infos_gin'),
        ),
    ]
