# Generated by Django 3.0.5 on 2020-05-02 15:48

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='uniq key', unique=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Families',
                'db_table': 'persons_families',
                'ordering': ('display_order', '-modified'),
            },
        ),
    ]
