# Generated by Django 3.0.2 on 2020-01-14 04:36

import attendees.persons.models.utility
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0003_price'),
        ('persons', '0003_relationship_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('apply_type', models.CharField(help_text='online or paper', max_length=20, null=True)),
                ('apply_key', models.CharField(help_text='E1T1F1 or #001', max_length=50, null=True)),
                ('donation', models.DecimalField(decimal_places=2, default=999999, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='occasions.Event')),
                ('main_attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Attendee')),
            ],
            options={
                'db_table': 'persons_registrations',
                'ordering': ('main_attendee__last_name', 'main_attendee__first_name'),
            },
            bases=(models.Model, attendees.persons.models.utility.Utility),
        ),
    ]
