# Generated by Django 3.0.2 on 2020-01-21 05:33

import attendees.persons.models.utility
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=999999, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('attending_type', models.CharField(max_length=20, null=True)),
                ('belief', models.CharField(max_length=20, null=True)),
                ('bed_needs', models.IntegerField(default=1)),
                ('mobility', models.IntegerField(default=0)),
                ('attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Attendee')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.Registration')),
            ],
            options={
                'db_table': 'persons_attendings',
                'ordering': ['registration'],
            },
            bases=(models.Model, attendees.persons.models.utility.Utility),
        ),
    ]
