# Generated by Django 3.0.5 on 2020-04-29 14:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_relation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('slug', models.SlugField(help_text='uniq key', blank=False, null=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True, help_text="from_relation_role would call to_relation_role what?")),
                ('display_order', models.SmallIntegerField(db_index=True, default=0)),
                ('emergency_contact', models.BooleanField(default=False, help_text="to_relation is from_relation's emergency_contact?")),
                ('scheduler', models.BooleanField(default=False, help_text="to_relation is from_relation's scheduler?")),
                ('from_relation_role', models.ForeignKey(on_delete=models.SET(0), related_name='from_relation_role', to='persons.RelationRole')),
                ('to_relation_role', models.ForeignKey(on_delete=models.SET(0), related_name='to_relation_role', to='persons.RelationRole')),
            ],
            options={
                'db_table': 'persons_relationship_defaults',
                'ordering': ('display_order', '-modified'),
            },
        ),
        migrations.AddField(
            model_name='relationrole',
            name='corresponding_relations',
            field=models.ManyToManyField(related_name='_relation_corresponding_relations_+', through='persons.RelationshipDefault', to='persons.RelationRole'),
        ),
        migrations.AddConstraint(
            model_name='relationshipdefault',
            constraint=models.UniqueConstraint(fields=('from_relation_role', 'to_relation_role'), name='from_relation_to_relation_role'),
        ),
    ]
