# Generated by Django 3.0.2 on 2020-01-21 05:33

import attendees.persons.models.utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=20, null=False, blank=False, default="normal", help_text="normal, not_going, coworker, etc")),
                ('belief', models.CharField(max_length=20, null=True, blank=True, help_text="believer, baptized, catechumen, etc")),
                ('bed_needs', models.IntegerField(null=False, blank=False, default=0, help_text="how many beds needed for this person?")),
                ('mobility', models.IntegerField(null=False, blank=False, default=200, help_text="walking up 3 floors is 300")),
                ('attendee', models.ForeignKey(null=False, blank=False, on_delete=models.SET(0), to='persons.Attendee')),
                ('registration', models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to='persons.Registration')),
            ],
            options={
                'db_table': 'persons_attendings',
                'ordering': ['registration'],
            },
            bases=(models.Model, attendees.persons.models.utility.Utility),
        ),
    ]
