# Generated by Django 3.0.2 on 2020-01-21 06:04

import attendees.persons.models.utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_attending_meet_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=models.SET(0), to='whereabouts.Address')),
                ('attendee', models.ForeignKey(on_delete=models.SET(0), to='persons.Attendee')),
                ('category', models.CharField(max_length=20, default='main', blank=False, null=False, help_text='main, resident, etc (main will be displayed first)')),
            ],
            options={
                'db_table': 'persons_attendee_addresses',
            },
            bases=(models.Model, attendees.persons.models.utility.Utility),
        ),
        migrations.AddField(
            model_name='attendee',
            name='addresses',
            field=models.ManyToManyField(through='persons.AttendeeAddress', to='whereabouts.Address', related_name='addresses'),
        ),
        migrations.AddConstraint(
            model_name='attendeeaddress',
            constraint=models.UniqueConstraint(fields=('attendee', 'address'), name='attendee_address'),
        ),
    ]
