# Generated by Django 3.0.2 on 2020-01-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0002_assembly_address'),
        ('whereabouts', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='assemblies',
            field=models.ManyToManyField(through='occasions.AssemblyAddress', to='occasions.Assembly'),
        ),
    ]
