# Generated by Django 3.0.2 on 2020-01-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0002_meet_address_m2m'),
        ('whereabouts', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='meets',
            field=models.ManyToManyField(through='occasions.MeetAddress', to='occasions.Meet'),
        ),
    ]
