# Generated by Django 3.0.2 on 2020-01-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_attendee_address'),
        ('whereabouts', '0008_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='attendees',
            field=models.ManyToManyField(through='persons.AttendeeAddress', to='persons.Attendee'),
        ),
    ]
