# Generated by Django 3.0.2 on 2020-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_attending_division_m2m'),
        ('whereabouts', '0008_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='attendings',
            field=models.ManyToManyField(through='persons.AttendingDivision', to='persons.Attending'),
        ),
    ]
