# Generated by Django 3.0.2 on 2020-01-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_attending_address'),
        ('whereabouts', '0009_division_attendings'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='attendings',
            field=models.ManyToManyField(through='persons.AttendingAddress', to='persons.Attending'),
        ),
    ]
