# Generated by Django 3.0.2 on 2020-01-14 05:01

import attendees.persons.models.utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0003_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('display_order', models.IntegerField(blank=True, default=0, null=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(db_index=True, default='normal', max_length=50)),
            ],
            options={
                'db_table': 'occasions_characters',
            },
            bases=(models.Model, attendees.persons.models.utility.Utility),
        ),
    ]
