# Generated by Django 3.0.2 on 2020-01-21 03:21

import attendees.persons.models.utility
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('occasions', '0005_meet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('is_removed', models.BooleanField(default=False)),
                ('display_name', models.CharField(blank=True, max_length=50, help_text="The Rock, Little Foot, singspiration, etc")),
                ('link', models.URLField(blank=True, null=True, max_length=254)),
                ('site_id', models.BigIntegerField()),
                ('meet', models.ForeignKey(on_delete=models.SET(0), to='occasions.Meet')),
                ('site_type', models.ForeignKey(help_text='location: django_content_type id for table name', on_delete=models.SET(0), to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'occasions_gatherings',
                'ordering': ['meet', 'start'],
            },
            bases=(models.Model, attendees.persons.models.utility.Utility),
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='gathering',
            constraint=models.UniqueConstraint(fields=('meet_id', 'site_type_id', 'site_id', 'start'), name='uniq_meet_location_time'),
        ),
    ]
