# Generated by Django 3.0.2 on 2020-03-27 04:49

import attendees.persons.models.utility
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('occasions', '0009_meet_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('assembly', models.ForeignKey(on_delete=models.SET(0), to='occasions.Assembly')),
                ('character', models.ForeignKey(on_delete=models.SET(0), to='occasions.Character')),
            ],
            options={
                'verbose_name_plural': 'Assembly Characters',
                'db_table': 'occasions_assembly_characters',
            },
            bases=(models.Model, attendees.persons.models.utility.Utility),
        ),
        migrations.AddField(
            model_name='assembly',
            name='characters',
            field=models.ManyToManyField(through='occasions.AssemblyCharacter', to='occasions.Character'),
        ),
        migrations.AddField(
            model_name='character',
            name='assemblies',
            field=models.ManyToManyField(through='occasions.AssemblyCharacter', to='occasions.Assembly'),
        ),
        migrations.AddConstraint(
            model_name='assemblycharacter',
            constraint=models.UniqueConstraint(fields=('assembly', 'character'), name='assembly_character'),
        ),
    ]
