from .page.datagrid_assembly_all_attendances import datagrid_assembly_all_attendances_list_view
# from .division.assembly_attendances_others import assembly_attendance_others_list_view
from .user.attendances import user_attendance_list_view
from .coworkers.organization_attendances import coworkers_organization_attendance_list_view
from .api.user_attendances import api_user_attendance_viewset
from .api.user_characters import api_user_character_viewset
from .api.user_gatherings import api_user_gathering_viewset
from .api.assembly_meet_attendances import api_assembly_meet_attendances_viewset
from .api.assembly_meet_characters import api_assembly_meet_characters_viewset
from .api.assembly_meet_teams import api_assembly_meet_teams_viewset
from .api.assembly_meet_gatherings import api_assembly_meet_gatherings_viewset
from .api.organization_teams import api_organization_team_viewset
from .api.organization_gatherings import api_organization_gathering_viewset
from .api.organization_characters import api_organization_character_viewset
from .api.organization_attendances import api_organization_attendance_viewset
